### ISSUE TITLE
process field not read correctly

### ISSUE THREAD

**Issue by tong** [electron/docs-parser#14]
`process` fields are not read correctly, currently always `true`.

https://github.com/electron/docs-parser/blob/d4d62e1ac0c32f732d0bde55e2ca06116490875b/src/DocsParser.ts#L164-L168

**Comment by MarshallOfSound** [comment]
Fixed in #17

**Comment by tong** [comment]
Wondering why this still isn't used in electron releases ? @MarshallOfSound
